Addition of requirements.txt and edits to readMe.md
byronkenoly/mechJobScraper pull request #2
Opened 2022-12-26 08:06 UTC by georgebangeboss

2022-12-26 16:47 UTC, byronkenoly requested changes
Update README.md
Add command for creating and activating virtual environment

2022-12-26 16:47 UTC, byronkenoly commented on README.md
> +2. Create virtual environment and activate it
Kindly add the command for creating and activating the virtual environment

2022-12-26 20:42 UTC, georgebangeboss commented on README.md
> +2. Create virtual environment and activate it
on it

2022-12-27 12:34 UTC, byronkenoly approved these changes
New file added: requirements.txt - contains dependencies required to run the program
Modified: README.md - beefed up documentation

Thanks for your contributions Mr. Bange

2022-12-27 12:34 UTC, merged